services:
  - type: web
    name: my-flask-app  # Change this to your app name
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PORT
        value: 10000
